import * as I from '../Interface';

const dataQuestions: I.Questions[] = [
  {
    id: 1,
    question: 'Which animal is known as the "Ship of the Desert"?',
    choices: ['Camel', 'Cat', 'Dog', 'Fog', 'Fox', 'Snake'],
    ans: 'Camel',
  },
  {
    id: 2,
    question: 'How many days are there in a week?',
    choices: ['6 days', '8 days', '31 days', '7 days', '28 days', '30 days'],
    ans: '7 days',
  },
  {
    id: 3,
    question: 'Which of the following is not an international organization?',
    choices: ['FIFA', 'UNICEF', 'ASEAN', 'FBI', 'UN', 'WHO'],
    ans: 'FBI',
  },
  {
    id: 4,
    question: 'Which of the following disorders is the fear of being alone?',
    choices: ['Agoraphobia', 'Aerophobia', 'Acrophobia', 'Arachnophobia', 'Zgoraphobia', 'Bgoraphobia'],
    ans: 'Agoraphobia',
  },
  {
    id: 5,
    question: 'How many hours are there in a day?',
    choices: ['24 hours', '12 hours', '6 hours', '48 hours', '120 hours', '1 hours'],
    ans: '24 hours',
  },
  {
    id: 6,
    question: 'How many letters are there in the English alphabet?',
    choices: ['44 letters', '26 letters', '25 letters', '24 letters', '30 letters', '36 letters'],
    ans: '26 letters',
  },
  {
    id: 7,
    question: 'Rainbow consist of how many colours?',
    choices: ['7 colours', '6 colours', '5 colours', '8 colours', '10 colours', '12 colours'],
    ans: '7 colours',
  },
  {
    id: 8,
    question: 'How many minutes are there in an hour?',
    choices: ['30 minutes', '24 minutes', '60 minutes', '120 minutes', '90 minutes', '48 minutes'],
    ans: '60 minutes',
  },
  {
    id: 9,
    question: 'How many seconds are there in a minute?',
    choices: ['30 seconds', '20 seconds', '120 seconds', '60 seconds', '120 seconds', '48 seconds'],
    ans: '60 seconds',
  },
  {
    id: 10,
    question: 'How many seconds make one hour?',
    choices: ['3400 seconds', '3600 seconds', '2400 seconds', '4800 seconds', '1200 seconds', '10000 seconds'],
    ans: '3600 seconds',
  },
  {
    id: 11,
    question: 'How many consonants are there in the English alphabet?',
    choices: ['21 Consonants', '26 Consonants', '44 Consonants', '20 Consonants', '25 Consonants', '30 Consonants'],
    ans: '21 Consonants',
  },
  {
    id: 12,
    question: 'Name the place known as the Roof of the World?',
    choices: ['Tibet', 'Thailand', 'USA', 'Japan', 'Sweden', 'Finland'],
    ans: 'Tibet',
  },
  {
    id: 13,
    question: 'Name the longest river on the Earth?',
    choices: ['Amazon', 'Nile', 'Alahoo', 'Valeto', 'Eslino', 'Ezpanilo'],
    ans: 'Nile',
  },
  {
    id: 14,
    question: 'Name the smallest continent?',
    choices: ['Africa', 'Europe', 'Asia', 'Australia', 'America', 'North America'],
    ans: 'Australia',
  },
  {
    id: 15,
    question: 'Which is the principal source of energy for the Earth?',
    choices: ['Sun', 'Earth', 'Magma', 'Wind', 'Sea', 'River'],
    ans: 'Sun',
  },
  {
    id: 16,
    question: 'Who invented electricity?',
    choices: [
      'Albert Einstein',
      'Benjamin Einstein',
      'Chalee Franklin',
      'Benjamin Franklin',
      'Necolas Davidenko',
      'Elon Musk',
    ],
    ans: 'Benjamin Franklin',
  },
  {
    id: 17,
    question: 'Name the National game of the USA?',
    choices: ['Baseball', 'Soccer', 'Volleyball', 'Football', 'Swim', 'Run'],
    ans: 'Baseball',
  },
  {
    id: 18,
    question: 'Who invented Watch?',
    choices: [
      'Peters Henlein',
      'Peterge Henlein',
      'Peterler Henlein',
      'Peter Henlein',
      'Peter Henleiner',
      'Peter Henleine',
    ],
    ans: 'Peter Henlein',
  },
  {
    id: 19,
    question: 'Name the country known as the Land of the Rising Sun?',
    choices: ['Japan', 'Thailand', 'Korea', 'USA', 'India', 'Germany'],
    ans: 'Japan',
  },
  {
    id: 20,
    question: 'How many millimeters are there in a centimeter?',
    choices: ['10mm', '100mm', '20mm', '25mm', '1mm', '1000mm'],
    ans: '10mm',
  },
  {
    id: 21,
    question: 'Who is the real founder of Microsoft?',
    choices: ['Bill Musk', 'Bill Gates and Paul G. Allen', 'Elon Musk', 'Steve Jobs', 'Bill Jobs', 'Json Gates'],
    ans: 'Bill Gates and Paul G. Allen',
  },
  {
    id: 22,
    question: 'Who gave the theory of Relativity?',
    choices: ['Albert Einstein', 'Albert Musk', 'Elon Musk', 'Elon Einstein', 'Albert Muskerberg', 'Bill Gate'],
    ans: 'Albert Einstein',
  },
  {
    id: 23,
    question: 'Who gave the universal law of gravitation?',
    choices: ['Albert Einstein', 'Albert Musk', 'Issac Newton', 'Elon Einstein', 'Elon Musk', 'Issac Skeleton'],
    ans: 'Issac Newton',
  },
  {
    id: 24,
    question: 'From which language is the word ‘ketchup’ derived?',
    choices: ['Japanese', 'Chinese', 'Thai', 'Sweden', 'English', 'Maya'],
    ans: 'Chinese',
  },
  {
    id: 25,
    question: 'Which is the country with the biggest population in Europe?',
    choices: ['Russia', 'Germany', 'Japan', 'China', 'USA', 'Brazil'],
    ans: 'Russia',
  },
  {
    id: 26,
    question: 'What colour are the four stars on the flag of New Zealand?',
    choices: ['Red', 'Yellow', 'Green', 'Blue', 'Pink', 'Orange'],
    ans: 'Red',
  },
  {
    id: 27,
    question: 'Which English football team plays its home matches at Old Trafford?',
    choices: ['Manchester City', 'Leed United', 'Arsenal', 'Manchester United', 'Luton Town', 'Barcelona'],
    ans: 'Manchester United',
  },
  {
    id: 28,
    question: 'H2O is the chemical formula for what?',
    choices: ['Water', 'Watermelon', 'Oil', 'Earth', 'Magma', 'Gas'],
    ans: 'Water',
  },
  {
    id: 29,
    question: 'Blandenburg, Bremen and Lower Saxony are states in which European country?',
    choices: ['Germany', 'USA', 'Sweden', 'Japan', 'Thailand', 'Finland'],
    ans: 'Germany',
  },
  {
    id: 30,
    question: 'Which German football team won the Champions League in 2013?',
    choices: ['Port FC', 'Real Madrid', 'Manchester United', 'Bayern Munich', 'Barcelona', 'PSG'],
    ans: 'Bayern Munich',
  },
  {
    id: 31,
    question: ' Which of the following personalities gave ‘The Laws of Heredity?    ',
    choices: ['G.J. Mendel', 'Robert Hook', 'Elon Musk', 'Charles Darwin', 'William Harvey', 'Gorge R Martin'],
    ans: 'G.J. Mendel',
  },
  {
    id: 32,
    question: 'Name the National bird of India?',
    choices: ['The Peacockers', 'The Ridge', 'The Bridge', 'The Rock', 'The Peacock', 'The Union'],
    ans: 'The Peacock',
  },
  {
    id: 33,
    question: 'Name the National animal of India?',
    choices: ['Tiger', 'Cat', 'Dog', 'Bird', 'Panda', 'Bear'],
    ans: 'Tiger',
  },
  {
    id: 34,
    question: 'Name the planet nearest to the Earth?',
    choices: ['Mercury', 'Sun', 'February', 'January', 'Potato', 'Pluto'],
    ans: 'Mercury',
  },
  {
    id: 35,
    question: 'Which is the tallest mountain in the world?',
    choices: ['Mount Everest', 'Mount Fuji', 'Mount Evergreen', 'Mount Riverest', 'Mount Neverest', 'Mount Inverest'],
    ans: 'Mount Everest',
  },
];

export default dataQuestions;
