export const GET_TABLE_SCORE_REQ = '@QUESTION/GET_TABLE_SCORE_REQ';
export const GET_TABLE_SCORE_SUCCESS = '@QUESTION/GET_TABLE_SCORE_SUCCESS';

export const SAVE_SCORE_REQ = '@QUESTION/SAVE_SCORE_REQ';
export const SAVE_SCORE_SUCCESS = '@QUESTION/SAVE_SCORE_SUCCESS';
export const SAVE_SCORE_FAIL = '@QUESTION/SAVE_SCORE_FAIL';

export const RANDOM_QUESTION_REQ = '@QUESTION/RANDOM_QUESTION_REQ';
export const RANDOM_QUESTION_SUCCESS = '@QUESTION/RANDOM_QUESTION_SUCCESS';
export const RANDOM_QUESTION_CLEAR = '@QUESTION/RANDOM_QUESTION_CLEAR';

export const NEXT_QUESTION_REQ = '@QUESTION/NEXT_QUESTION_REQ';
export const NEXT_QUESTION_SUCCESS = '@QUESTION/NEXT_QUESTION_SUCCESS';

export const NEW_ROUND_QEQ = '@QUESTION/NEW_ROUND_REQ';
export const NEW_ROUND_SUCCESS = '@QUESTION/NEW_ROUND_SUCCESS';

export const EXIT_CURRENT_ROUND_REQ = '@QUESTION/EXIT_CURRENT_ROUND_REQ';
export const EXIT_CURRENT_ROUND_SUCCESS = '@QUESTION/EXIT_CURRENT_ROUND_SUCCESS';

export const CLEAR_SCORE_REQ = '@QUESTION/CLEAR_SCORE_REQ';
export const CLEAR_SCORE_SUCCESS = '@QUESTION/CLEAR_SCORE_SUCCESS';
